/**
 * ApprovalExpired Component
 * Displayed when an approval link has expired
 */

import { Clock, AlertTriangle, Mail, Phone } from 'lucide-react'
import { formatDate } from '../../utils/formatters'

// =============================================================================
// TYPES
// =============================================================================

export interface ApprovalExpiredProps {
  projectName: string
  approvalStage: string
  expiresAt: string
  contactEmail?: string
  contactPhone?: string
}

// =============================================================================
// COMPONENT
// =============================================================================

export function ApprovalExpired({
  projectName,
  approvalStage,
  expiresAt,
  contactEmail,
  contactPhone
}: ApprovalExpiredProps) {
  return (
    <div className="min-h-screen bg-gray-50 flex items-center justify-center p-4">
      <div className="max-w-md w-full">
        {/* Main card */}
        <div className="bg-white rounded-lg shadow-lg overflow-hidden">
          {/* Status banner */}
          <div className="bg-gray-600 px-6 py-8 text-center">
            <div className="w-16 h-16 mx-auto mb-4 bg-white/20 rounded-full flex items-center justify-center">
              <Clock className="w-8 h-8 text-white" />
            </div>
            <h1 className="text-2xl font-bold text-white mb-2">
              Approval Expired
            </h1>
            <p className="text-white/90">
              This approval link is no longer valid
            </p>
          </div>

          {/* Details */}
          <div className="px-6 py-6 space-y-4">
            {/* Project info */}
            <div>
              <h2 className="text-lg font-semibold text-gray-900">
                {projectName}
              </h2>
              <p className="text-gray-600">{approvalStage}</p>
            </div>

            {/* Expiry date */}
            <div className="flex items-center gap-2 text-sm text-gray-500">
              <Clock size={16} />
              <span>Expired on {formatDate(expiresAt)}</span>
            </div>

            {/* Warning message */}
            <div className="bg-amber-50 border border-amber-200 rounded-lg p-4">
              <div className="flex gap-3">
                <AlertTriangle className="w-5 h-5 text-amber-600 flex-shrink-0 mt-0.5" />
                <div className="text-amber-800">
                  <p className="font-medium mb-1">What should I do?</p>
                  <p className="text-sm">
                    Please contact the project team to request a new approval link. 
                    They can resend the approval request with an updated expiry date.
                  </p>
                </div>
              </div>
            </div>

            {/* Contact options */}
            {(contactEmail || contactPhone) && (
              <div className="space-y-2">
                <p className="text-sm font-medium text-gray-700">Contact the team:</p>
                
                {contactEmail && (
                  <a
                    href={`mailto:${contactEmail}?subject=New%20approval%20link%20needed%20-%20${encodeURIComponent(projectName)}`}
                    className="flex items-center gap-2 text-green-600 hover:text-green-700 text-sm"
                  >
                    <Mail size={16} />
                    <span>{contactEmail}</span>
                  </a>
                )}
                
                {contactPhone && (
                  <a
                    href={`tel:${contactPhone}`}
                    className="flex items-center gap-2 text-green-600 hover:text-green-700 text-sm"
                  >
                    <Phone size={16} />
                    <span>{contactPhone}</span>
                  </a>
                )}
              </div>
            )}
          </div>

          {/* Footer */}
          <div className="px-6 py-4 bg-gray-50 border-t border-gray-200">
            <p className="text-xs text-gray-500 text-center">
              Approval links expire for security reasons. A new link can be 
              generated by the project team.
            </p>
          </div>
        </div>

        {/* Branding */}
        <p className="text-center text-sm text-gray-500 mt-6">
          Powered by{' '}
          <a 
            href="https://approv.co.uk"
            className="text-green-600 hover:text-green-700 font-medium"
            target="_blank"
            rel="noopener noreferrer"
          >
            Approv
          </a>
        </p>
      </div>
    </div>
  )
}

// =============================================================================
// INLINE EXPIRED WARNING
// =============================================================================

export interface ExpiredWarningProps {
  expiresAt: string
  className?: string
}

export function ExpiredWarning({ expiresAt, className = '' }: ExpiredWarningProps) {
  return (
    <div className={`bg-red-50 border border-red-200 rounded-lg p-4 ${className}`}>
      <div className="flex gap-3">
        <Clock className="w-5 h-5 text-red-600 flex-shrink-0" />
        <div>
          <p className="font-medium text-red-800">This approval has expired</p>
          <p className="text-sm text-red-700 mt-1">
            The approval link expired on {formatDate(expiresAt)}. 
            Please contact the project team for a new link.
          </p>
        </div>
      </div>
    </div>
  )
}

// =============================================================================
// EXPIRING SOON WARNING
// =============================================================================

export interface ExpiringSoonWarningProps {
  expiresAt: string
  className?: string
}

export function ExpiringSoonWarning({ expiresAt, className = '' }: ExpiringSoonWarningProps) {
  const expiryDate = new Date(expiresAt)
  const now = new Date()
  const daysRemaining = Math.ceil((expiryDate.getTime() - now.getTime()) / (1000 * 60 * 60 * 24))

  if (daysRemaining > 7) return null

  return (
    <div className={`bg-amber-50 border border-amber-200 rounded-lg p-4 ${className}`}>
      <div className="flex gap-3">
        <AlertTriangle className="w-5 h-5 text-amber-600 flex-shrink-0" />
        <div>
          <p className="font-medium text-amber-800">
            {daysRemaining <= 1 
              ? 'Expires today!' 
              : `Expires in ${daysRemaining} days`
            }
          </p>
          <p className="text-sm text-amber-700 mt-1">
            Please review and respond before {formatDate(expiresAt)} to avoid needing a new link.
          </p>
        </div>
      </div>
    </div>
  )
}

export default ApprovalExpired
